version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1001
      context: ./
      dockerfile: Dockerfile.dev
    image: pequi
    container_name: pequi-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - pequi

  nginx:
    image: nginx:alpine
    container_name: pequi-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - pequi

networks:
  pequi:
    driver: bridge