name: Laravel Static Build

on:
  push:
    branches: [ laravel ]
  pull_request:
    branches: [ laravel ]

jobs:
  build-test-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - 
      name: Build the site in the jekyll/builder container
      run: |
        docker build -t pequi/laravel:latest -f Dockerfile.dev .
        docker run \
        -v ${{ github.workspace }}:/var/www -v ${{ github.workspace }}/dist:/var/www/dist \
        pequi/laravel:latest /bin/bash -c "./install-dependencies.sh"
    -
      name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v3
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        git-user-signingkey: true
        git-commit-gpgsign: true
    -
      name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: laravel-dist
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
